## Question 14.2

In Java, does the finally block get executed if we insert a return statement inside the try block of a try-catch-finally?

## Solution

実行される。

finally ブロックは try ブロック実行終了時に呼び出されるため、 return を try ブロック内で実行して抜け出すことを明示しても finally ブロック内の処理は実行されます。

ただし、下記の2パターンでは実行されません。

1. finally ブロック実行前に **仮想マシン** が終了した場合
1. finally ブロック実行前に **プロセス** が終了した場合
